ALTER TABLE KHACHHANG
ADD CONSTRAINT chk_dt_10 CHECK (LEN(DT) <= 10);

ALTER TABLE VATTU
ADD CONSTRAINT chk_giamua CHECK (GIAMUA > 0)

ALTER TABLE VATTU
ADD CONSTRAINT chk_slton CHECK (SLTON >= 0)

ALTER TABLE HOADON
ADD FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE CHITIETHOADON
ADD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

ALTER TABLE CHITIETHOADON
ADD FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT chk_sl CHECK (SL > 0)


